{
 "title": "Mysql Pod Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL Pod Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"default\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "MySQL Commands",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_commands_total{command=\"create_db\"}",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "mysql_global_status_commands_total{command=\"drop_db\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "MYSQL Handler Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_handlers_total{handler=\"write\"}",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "mysql_global_status_handlers_total{handler=\"delete\"}",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "mysql_global_status_handlers_total{handler=\"update\"}",
     "legendFormat": "{{handler}}"
    },
    {
     "expr": "mysql_global_status_handlers_total{handler=\"commit\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "MySQL Slow Log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_slow_query_log",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}